task:
  name: vqa
  #debug: 10
  chooser: cvpr # [null, cvpr, naacl]
  answers: 2000
  input_path: /media/evl/Public/Mahyar/Data/CVPRdata/CUB_200_2011/CUB_200_2011/convs_nc
  image_path: /media/evl/Public/Mahyar/Data/CVPRdata/CUB_200_2011/CUB_200_2011/images
  load_normalizer: /media/evl/Public/Mahyar/Data/CVPRdata/normalizer_data.npz
  load_train: /media/evl/Public/Mahyar/Data/CVPRdata/batches
  load_val: /media/evl/Public/Mahyar/Data/CVPRdata/batches/val
  load_test: /media/evl/Public/Mahyar/Data/CVPRdata/batches3/test
  parse_path: /media/evl/Public/Mahyar/Data/CVPRdata/sps2
  prepare_indices: false
  load_indices: data/
  save_indices: false
  save_net: 1

model:
  name: nmn
  lstm_hidden: 1000
  layout_hidden: 100
  att_hidden: 100
  #pred_hidden: 500
  combine_question: false
  att_normalization: local
  #load_model: data/model_9.h5
  #load_adastate: data/model_9_adastate

opt:
  batch_size: 800
  iters: 100
  dropout: true
  multiclass: false

  rho: 0.90
  eps: 0.000001
  lr: 1
  clip: 10.0
