task:
  name: vqa
  #debug: 1013
  chooser: cvpr # [null, cvpr, naacl]
  answers: 2000
  load_normalizer: /media/evl/Public/Mahyar/Data/vqa/normalizer_data.npz
  load_train: train2014
  load_val: val2014
  load_test: test2014
  prepare_indices: false
  load_indices: data/

model:
  name: nmn

  lstm_hidden: 1000
  layout_hidden: 100
  att_hidden: 100
  pred_hidden: 500

  combine_question: false
  att_normalization: local
  load_model: data/model_1.h5

opt:
  batch_size: 500
  iters: 30
  dropout: true
  multiclass: false

  rho: 0.95
  eps: 0.000001
  lr: 1
  clip: 10.0
